### ISSUE TITLE
Support for Replica items icons?

### ISSUE THREAD

**Issue by darinrandal** [meta-is-beta/horadric-helper#27]
Hi, I was recently trying to set up a number of items with Horadric Helper and noticed that when using data for the item it doesn't recognize the replica part. Searching through the readme shows it does support replica but doesn't seem to parse it from the data attribute and include the icon in the header.

Is there a better way to set up uniques than this?

This is what I was testing:

```
<poe-item as-icon reference="replica-bated-breath"></poe-item>

<script>
window.HoradricHelper.PathOfExile.applyConfig([
  {
    reference: "replica-bated-breath",
    iconUrl: "/assets/img/horadric-helper/BatedBreath.png",
    data: `Item Class: Belts
    Rarity: Unique
    Replica Bated Breath
    Chain Belt
    --------
    Requirements:
    Level: 22
    --------
    Item Level: 80
    --------
    +15 to maximum Energy Shield (implicit)
    --------
    -23 to Intelligence
    10% increased Damage
    50% increased Fishing Pool Consumption
    20% increased Fishing Range
    26% increased Rarity of Fish Caught
    --------
    "I cannot fathom the mysteries of Prototype #16. It did nearly nothing until I
    brought it to [RESTRICTED]. It makes no sense!"
    - Researcher Graven`
  }
]);
</script>
```

You can check out what I'm trying to do over here: https://poe-fish.pages.dev/horadric-helper-test/. I'm working on migrating https://poe.fish/fishing-items (old hideous version) over to a new platform (Jekyll) for speed/seo/ease of use.

Couple other questions:
- Do you have any idea how to center the horadric helper items vertically and centered in their card containers like shown on the above link? Trying to come up with a good idea of how to show all this info.
- Keystones seem to behave differently than the poe-items as far as the container that they get generated in.
- Do you plan on supporting divination cards down the road?

**Comment by meta-is-beta** [comment]
Replica is not an influence so it's not getting detected. I will probably add detection from item's name in the next release, but it will only work with English item names. Until then you can do a workaround by adding `Replica Item` after flavor text.

```
...
20% increased Fishing Range
26% increased Rarity of Fish Caught
--------
"I cannot fathom the mysteries of Prototype #16. It did nearly nothing until I
brought it to [RESTRICTED]. It makes no sense!"
- Researcher Graven`
--------
Replica Item
```

Other questions:
- Normal tab in PoE is 12-slots long - most css grid systems use 12 columns. I would take advantage of that fact and wrap each item/passive in a container that takes-up appropriate amount of columns in a grid. For example here is a Bootstrap 5 grid system: [https://getbootstrap.com/docs/5.0/layout/grid/](https://getbootstrap.com/docs/5.0/layout/grid/). And as for centering items/passives within containers - Flexbox is your friend.
- Ye, I think I know what you mean, I will investigate. 
- Wasn't planning on adding them, but I will look into how much work that would be.
